### PR TITLE
Add support for "and" and "or" predicates

### PR DESCRIPTION
**Pull request by alloveras**
## Context
Support for `AND` predicates was added as part of https://github.com/tfsec/tfsec/pull/580. 

## Intent
To re-work the current implementation for composite checks.

## Problem
The major downsides we found with the current implementation are:
- Some custom checks may benefit from an `or` operator being available.
- The implicit `and` behavior of `subMatches` is not apparent from the check definition files. In consequence, non-experienced users will struggle to understand/write checks without having to refer to the official documentation or rely on their teams' tribal knowledge.
- The `subMatch` / `subMatches` operator is a bit overloaded with too many responsibilities:
    -  Provide the ability to “look into” a nested block. 
    -  Provide support for `and`-based composite boolean expressions.

## Proposed Solution
To adopt a new implementation for composite checks that supports both `and` and `or` operators, it is explicitly visible from the check definition files, and do not overload the `subMatch` operator keeping the `chekFunctions` as atomic as possible.

As you can see from the check_all_statements_test.go file, it will still be possible to provide the same functionality that `subMatches` had provided, while allowing for general checkFunctions to be combined. 

(cc: @muplim)

### CODE REVIEW

**Comment by owenrumney** [comment]
This makes sense, thank @alloveras - Could you update the documentation to reflect this change as well please - https://github.com/tfsec/tfsec/blob/master/docs-website/docs/config/custom_checks.md

@felipesere  - this will be relevant to you as it would be a breaking change to your new addition. I think given its early stages I trust that won't impact you too heavily

**Comment by felipesere** [comment]
This looks really good! I'd be happy for this!

**Review by owenrumney — CHANGES_REQUESTED** [review]
All good - just the doc to update - https://github.com/tfsec/tfsec/blob/master/docs-website/docs/config/custom_checks.md

**Comment by alloveras** [comment]
> All good - just the doc to update - https://github.com/tfsec/tfsec/blob/master/docs-website/docs/config/custom_checks.md

Sure, no problem. I will get to that as soon as I have some spare minutes and send it back for a final review.

**Comment by alloveras** [comment]
Hey @owenrumney,
I added the changes to the documentation you requested.

Do you mind having another look?

Thanks!

**Comment by owenrumney** [comment]
This is great, thanks @alloveras  - will cut it as v0.38.1

**Comment by alloveras** [comment]
No worries @ owenrumney 👍 

Actually, we have another PR incoming (next couple of minutes) that I'd like to consider for 0.38.1. 

Would you mind taking a look before cutting the release?

**Comment by owenrumney** [comment]
I already cut one, but happy to do the next once you've raised your PR

Will keep an eye out

**Pull request merged**
