### PR TITLE
Switch to using scratch for docker base image

### PR DESCRIPTION
**Pull request by pujan14**
Signed-off-by: Pujan Shah <pujan14@gmail.com>

Switch to using scratch for docker base image.

### CODE REVIEW

**Comment by owenrumney** [comment]
Hey @pujan14, thanks for the PR. I’m not sure this is something we want to do. I think the benefits of alpine with a nobody user offer more flexibility for downstream users.

thoughts @liamg ?

**Comment by pujan14** [comment]
Hi @owenrumney,
I think in this case docker is used only as packaging/distribution format. There are no dependencies inside container and usually downstream users will not need to change anything inside container so I don't see any advantage of using alpine.

**Comment by owenrumney** [comment]
@pujan14 we actually use it in a downstream suite where we mount override the entry point to suit our needs. That would be much more difficult as a scratch image.

that said, this might be a good opportunity to update travis to write multiple flavours of the docker image. Will look at that in the morning

**Comment by owenrumney** [comment]
Hey @pujan14  - I've added `tfsec/tfsec-alpine` and `tfsec/tfsec-scratch` to the build. We discussed and we don't want to change the existing one because it may impact more downstream users than just us.

Thanks for the PR, it prompted us to do this

**Pull request closed without merging**
