### PR TITLE
Fixed recursive directory scanning regression

### LINKED ISSUE #567: Latest version does not appear to crawl directory hierarchy recursively like previous version
**Describe the bug**
I am using latest stable v0.37.1 and comparing against a previous version (v0.27.0) I was using and had various integration tests configured for. Previously I was getting findings for `.tf` files in sub-directories from the directory specified at the command line, now it appears that it does not crawl all files

**To Reproduce**
1. `tfsec ./some-dir-with-sub-dirs/`

**Expected behavior**
Get findings for `.tf` files located all the way down the hierarchy

**Desktop (please complete the following information):**
 - OS: macOS Big Sur

### PR DESCRIPTION
**Pull request by fproulx-boostsecurity**
Fixes #567

### CODE REVIEW

**Review by liamg — APPROVED** [review]

**Review by liamg — COMMENTED** [review]
After some thought, this needs further discussion, will review shortly.

**Comment by fproulx-boostsecurity** [comment]
In fact we integrated in our fork but noticed duplicates. So the rest of the code does not play well with this. As resources inside modules are scanned as in the module and standalone. So we have duplicates. Not sure how to fix that though.

**Comment by daroga0002** [comment]
doesnt this was arleady fixed ini https://github.com/tfsec/tfsec/issues/567 ?

**Comment by owenrumney** [comment]
@fproulx-boostsecurity  - I think this is solved - are you okay for this to be closed?

**Pull request closed without merging**
